spring:
  datasource:
    username: root
    password: 123456789
    url: jdbc:mysql://localhost:3306/lottery?useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
nacos:
  discovery:
    server-addr: 127.0.0.1:8848
dubbo:
  application:
    name: Lottery
    version: 1.0.0
  #    parameters:
  #      unicast: false
  registry:
#    address: multicast://224.5.6.7:1234
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: com.lu.rpc.*
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: on   #开启
  mapper-locations: classpath:/mapper/*.xml